server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: selmag-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@192.168.0.108:8888