server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.120:27017/feedback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag