server:
  port: 8084
spring:
  application:
    name: selmag-feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888