server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.120:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: AniOsr2LTXVVb9oSZRF1JT23tyAPC1Z0
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: AniOsr2LTXVVb9oSZRF1JT23tyAPC1Z0
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus