selmag:
  services:
    catalogue:
      uri: lb://selmag-catalogue-service
    feedback:
      uri: lb://selmag-feedback-service
server:
  port: 8083
spring:
  application:
    name: selmag-customer-app
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: customer-app
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.120:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: oFwH54m13hwXZmVj6I0itYcuOy2fFeVU
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: XE6IWwQgQ8kB5j0g78VoOjPGK8l08rBY
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.0.120:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true