spring:
  datasource:
    url: jdbc:postgresql://192.168.0.120:5432/catalogue
    username: postgres
    password: mysecretpassword
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag
server:
  port: 8081
logging:
  level:
    sql: info