server:
  port: 8888
spring:
  application:
    name: selmag_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kushlenkov/selmag_confg.git
          clone-on-start: true
          default-label: master
          search-paths:
            - '{application}/{profile}'